# =====================
# age-plugin-yubikey → PR #215 (post-quantum `mlkem768p256tag` identities)
# with PR #236 (the `yubikey` 0.9 bump that unlocks AES management keys)
# merged on top
# =====================
#
# Two things released `age-plugin-yubikey` 0.5.1 can't do, both of which we
# need on this host:
#
#  1. AES management keys. YubiKey 5.7+ ships with an AES-192 PIV management
#     key, but 0.5.1 pins `yubikey = 0.8.0-pre.0`, whose `MgmKey` is 24 bytes
#     of 3DES and whose `authenticate()` hardcodes ALGO_3DES in the APDU — the
#     crate contains no AES code at all. So `key::manage()` fails to
#     authenticate with the default key and bails out telling you to run
#     `ykman piv access change-management-key -a TDES --protect`. See upstream
#     issues #92 and #237. Fixed by `yubikey` 0.9.0-pre.0, which grew
#     `MgmAlgorithmId` and picks AES-192 for 5.7+ firmware.
#  2. Post-quantum recipients. `age` 1.3 specifies `mlkem768p256tag`
#     (`age1tagpq1..`, ML-KEM-768 + P-256 hybrid); upstream `main` implements
#     only its classical sibling `p256tag` (`age1tag1..`).
#
# Neither is released, and no single branch has both, so this overlay stitches
# them together:
#
#   src   = PR #215 head, str4d's own `mlkem768p256tag` branch. It's the larger
#           diff (~3k lines, incl. the KEM and its test vectors) and it's based
#           on the merged #213, so it makes the better base.
#   patch = PR #236 (Warfront1's `yubikey` 0.9 migration, which also drags in
#           the x509-parser → x509-cert rewrite), rebased onto that branch, plus
#           the `main` commits #215 predates.
#
# The two PRs conflict for a real reason, not just textually: #215 stores the
# ML-KEM seed in a critical X.509 extension of the slot certificate (YubiKeys
# can't hold ML-KEM keys themselves), which it writes and parses with the
# `x509`/`x509-parser` crates that #236 deletes. The conflict resolutions in
# the patch port that extension handling — plus `identify_recipient`'s
# known-OID check, the seed encode/extract pair, `Recipient::from_spki`, and
# the certificate builder's extension plumbing — over to `x509-cert` 0.3. The
# DER on the wire is unchanged (OCTET STRING, tag 0x04, len 0x40, seed), so
# identities generated by an unpatched #215 build still decrypt here.
#
# Both upstream PRs are open, so this is a snapshot, not a pin to anything
# stable. When either lands, drop the corresponding half — the rebuild will
# fail loudly, since the patch hunks won't apply.
final: prev:
let
  # PR #215 head: "Make `tagpq` the default identity type with config options".
  rev = "f825555fff3ec21f58233b366ea6017ca4938ede";
  # Dated after the newest commit the patch carries (PR #236, 2026-07-29).
  version = "0.5.1-unstable-2026-07-29";
  # #215 patches `age-core`/`age-plugin` to a rage revision with the HPKE
  # primitives the tagged recipient types need; both resolve to the same git
  # tree, so they share one hash.
  rageSrcHash = "sha256-8ofjDAXt5+LY+okaclSbZuS/nncqFl3pEYgVvN3syCY=";
in
{
  age-plugin-yubikey = prev.age-plugin-yubikey.overrideAttrs (old: {
    inherit version;

    src = final.fetchFromGitHub {
      owner = "str4d";
      repo = "age-plugin-yubikey";
      inherit rev;
      hash = "sha256-s5lUbAPTHIdON7I9wdD64mSzxdqLiDbdp3yCEDWgkCU=";
    };

    patches = (old.patches or [ ]) ++ [ ./yubikey-0.9-aes-mgmt-key.patch ];

    # The patch deliberately leaves Cargo.lock alone — the resolved lockfile is
    # ~1.1k lines of diff and would bury the source changes — so drop in the
    # merged one instead. It has to land before cargoSetupPostPatchHook runs,
    # which it does: `runHook postPatch` evaluates this attribute first.
    postPatch = (old.postPatch or "") + ''
      cp ${./Cargo.lock} Cargo.lock
    '';

    cargoDeps = final.rustPlatform.importCargoLock {
      lockFile = ./Cargo.lock;
      outputHashes = {
        "age-core-0.11.0" = rageSrcHash;
        "age-plugin-0.6.1" = rageSrcHash;
      };
    };

    meta = old.meta // {
      changelog = "https://github.com/str4d/age-plugin-yubikey/pull/215";
    };
  });
}
